### ISSUE TITLE
Create Infra Provider form uses cache values from other forms/pages

### ISSUE THREAD

**Issue by valaparthvi** [rancher/capi-ui-extension#45] opened 2024-04-15 09:40 UTC
While creating an infrastructure provider, I noticed it uses cache values from other forms/pages, mainly for namespaces and cloud credentials.

Version Information:
CAPI UI: v0.4.0
RT: v0.6.0
Rancher: v2.8-head(59bef33)

Steps to reproduce:
1. Add at least 2 cloud credentials.
2. Create an infrastructure provider. Note the values for namespace(=default) and cloud credential.
3. Go to continuous delivery, change the namespace to `fleet-local` and add a repo.
4. Start creating another infrastructure provider.
5. Note the namespace value, it should now be `fleet-local` instead of `default`. Note the cloud credential value, it's value is the cloud credentials ID selected previously. (_There is another bug here, where it displays the cloudcred ID instead of name which is not very user friendly._)

Apparently it only takes the value set in the Cluster Management page and is not affected by other pages.

![Screenshot from 2024-04-15 15-08-59](https://github.com/rancher/capi-ui-extension/assets/11015077/de76d818-aecc-4642-ad5d-b5a7248246e9)

**Comment by eva-vashkevich** [comment] 2024-04-20 00:38
The cloudcred id being shown instead of name seems to be Amazon-specific and can be seen in the rest of dashboard as well. I will open a bug there

**Comment by valaparthvi** [comment] 2024-04-22 04:06
> The cloudcred id being shown instead of name seems to be Amazon-specific and can be seen in the rest of dashboard as well. I will open a bug there Edit: Or maybe not. It still looks like a dashboard issue and not CAPI ui issue

Yes, I noticed that too. It does not appear the first time you create provider, but on second attempt or when creating an Azure provider, it does.

**Comment by eva-vashkevich** [comment] 2024-05-08 18:22
Hi @valaparthvi are you still able to reproduce it on latest version?

**Comment by eva-vashkevich** [comment] 2024-05-08 18:27
Also, if credential is created without providing a name, which is not mandatory, we will be just displaying ID. I think I saw credentials that have a name be shown as ids, but I can't reproduce that, so will need to keep an eye on that happening

**Comment by valaparthvi** [comment] 2024-05-09 07:31
@eva-vashkevich I cannot reproduce the issue for cloud credentials, but I can still see that the issue is true for namespace.

When I first create a provider, the selected namespace is default, but if I go to Continuous delivery, select `fleet-local` add a repository, come back to create a provider, the selected namespace becomes `fleet-local`. If I select any other namespace and create the provider, the next time I open create provider form, the namespace value is the one selected previously.

[Screencast from 05-09-2024 12:59:59 PM.webm](https://github.com/rancher/capi-ui-extension/assets/11015077/52c25729-eec4-4b63-a47a-6d674136edd9)

**Comment by eva-vashkevich** [comment] 2024-05-09 18:14
I believe this is expected behavior of the cloud credentials. It uses the ns that was last used because we assume that the user would want to continue using that same namespace.
@mantis-toboggan-md could you please confirm that this is intentional?

**Comment by mantis-toboggan-md** [comment] 2024-05-09 19:46
That's correct @eva-vashkevich this is intentional behavior across the dashboard.

**Comment by eva-vashkevich** [comment] 2024-05-09 19:49
Closing as this is intentional behavior and the other issue is no longer reproducible.

**Closed by eva-vashkevich** 2024-05-09 19:49 UTC
Labels: kind/bug, area/ui
